modLoader="javafml"
loaderVersion="[47,)" # compatible with Forge 1.20.1
license="MIT License"

[[mods]]
modId="bob"
version="1.0.0"
displayName="bob!"
authors="lexthedev"
description='''
a funky little guy named bob who just walks around and says hi
'''

[[dependencies.bob]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.bob]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"